import type { ThemeConfig } from './theme-types';

export const themesPart2: Record<string, ThemeConfig> = {
  food: {
    id: 'food',
    name: 'Saveurs',
    niche: 'Alimentation & Restauration',
    storeName: 'Saveurs d\'Afrique',
    heroTitle: 'Les saveurs authentiques',
    heroSubtitle: 'Produits locaux, bio et du terroir',
    heroImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=80',
    heroCta: 'Découvrir les saveurs',
    richTextHeading: 'Du producteur à votre table',
    richTextContent: 'Nous travaillons directement avec les producteurs locaux pour vous offrir des produits frais, bio et authentiques.',
    aboutTitle: '100% local & bio',
    aboutContent: 'Traçabilité garantie. Des producteurs de la Zone CFA à votre cuisine.',
    promoBanner: 'Produits frais — Livraison le jour même à Dakar',
    newsletterTitle: 'Recettes et actualités du terroir',
    contactEmail: 'saveurs@saveursafrique.com',
    contactPhone: '+221 77 XXX XX XX',
    colors: { primary: '#2d5016', secondary: '#7cb342', accent: '#ff8f00', bg: '#f5f5dc', text: '#2d5016' },
    products: [
      { id: '1', name: 'Miel pur local', price: 8000, priceLabel: '8 000 XOF', description: '500g', imagePlaceholder: '🍯', imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&q=80' },
      { id: '2', name: 'Café torréfié', price: 12000, priceLabel: '12 000 XOF', description: '1 kg', imagePlaceholder: '☕', imageUrl: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=600&q=80' },
      { id: '3', name: 'Épices du marché', price: 3500, priceLabel: '3 500 XOF', description: 'Assortiment', imagePlaceholder: '🧂', imageUrl: 'https://images.unsplash.com/photo-1596040033229-a0b857ab8a21?w=600&q=80' },
      { id: '4', name: 'Chocolat artisanal', price: 6000, priceLabel: '6 000 XOF', description: 'Tablette 100g', imagePlaceholder: '🍫', imageUrl: 'https://images.unsplash.com/photo-1606312619070-d48b4d652a52?w=600&q=80' },
      { id: '5', name: 'Fruits secs', price: 4500, priceLabel: '4 500 XOF', description: 'Mélange premium', imagePlaceholder: '🥜', imageUrl: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=600&q=80' },
      { id: '6', name: 'Jus naturel', price: 2500, priceLabel: '2 500 XOF', description: '1L frais', imagePlaceholder: '🧃', imageUrl: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=600&q=80' },
    ],
    footerTagline: 'Saveurs d\'Afrique — Du producteur à votre table',
    footerLinks: [
      { label: 'Accueil', href: '/' },
      { label: 'Produits', href: '/products' },
      { label: 'À propos', href: '/about' },
      { label: 'Contact', href: '/contact' },
    ],
    collections: [
      { id: 'all', name: 'Tous les produits', productIds: ['1', '2', '3', '4', '5', '6'] },
      { id: 'boissons', name: 'Boissons', productIds: ['1', '2', '6'] },
      { id: 'gourmandises', name: 'Gourmandises', productIds: ['3', '4', '5'] },
    ],
  },
  beaute: {
    id: 'beaute',
    name: 'Beauté',
    niche: 'Cosmétiques & Soins',
    storeName: 'Beauté Noire',
    heroTitle: 'Prenez soin de vous',
    heroSubtitle: 'Cosmétiques naturels adaptés aux peaux africaines',
    heroImage: 'https://images.unsplash.com/photo-1596462502278-fbfbdc04619d?w=1200&q=80',
    heroCta: 'Voir la gamme',
    richTextHeading: 'Naturellement vous',
    richTextContent: 'Des soins formulés avec des ingrédients naturels africains : karité, huile de coco, beurre de cacao. Pour une beauté authentique.',
    aboutTitle: 'Formules 100% naturelles',
    aboutContent: 'Sans parabènes, sans sulfates. Des produits testés et approuvés.',
    promoBanner: 'Offre découverte — -15% sur votre 1ère commande',
    newsletterTitle: 'Conseils beauté et nouveautés',
    contactEmail: 'beaute@beautenoire.com',
    contactPhone: '+221 78 XXX XX XX',
    colors: { primary: '#4a1942', secondary: '#7b2cbf', accent: '#e0aaff', bg: '#fdf5ff', text: '#4a1942' },
    products: [
      { id: '1', name: 'Crème hydratante karité', price: 12000, priceLabel: '12 000 XOF', description: '100% naturelle', imagePlaceholder: '🧴', imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80' },
      { id: '2', name: 'Huile de coco', price: 8500, priceLabel: '8 500 XOF', description: 'Cheveux & corps', imagePlaceholder: '🫒', imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80' },
      { id: '3', name: 'Savon noir traditionnel', price: 2500, priceLabel: '2 500 XOF', description: 'Purifiante', imagePlaceholder: '🧼', imageUrl: 'https://images.unsplash.com/photo-1584305574647-0cc949dc0936?w=600&q=80' },
      { id: '4', name: 'Masque capillaire', price: 15000, priceLabel: '15 000 XOF', description: 'Repousse', imagePlaceholder: '💆', imageUrl: 'https://images.unsplash.com/photo-1522338242762-41d2e6728f67?w=600&q=80' },
      { id: '5', name: 'Parfum doux', price: 22000, priceLabel: '22 000 XOF', description: 'Notes florales', imagePlaceholder: '🌸', imageUrl: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&q=80' },
      { id: '6', name: 'Baume à lèvres', price: 3500, priceLabel: '3 500 XOF', description: 'Karité & miel', imagePlaceholder: '💄', imageUrl: 'https://images.unsplash.com/photo-1631214524026-68e6197382bd?w=600&q=80' },
    ],
    footerTagline: 'Beauté Noire — Naturellement vous',
    footerLinks: [
      { label: 'Accueil', href: '/' },
      { label: 'Produits', href: '/products' },
      { label: 'À propos', href: '/about' },
      { label: 'Contact', href: '/contact' },
    ],
    collections: [
      { id: 'all', name: 'Toute la gamme', productIds: ['1', '2', '3', '4', '5', '6'] },
    ],
  },
  artisanat: {
    id: 'artisanat',
    name: 'Artisanat',
    niche: 'Créations & Handmade',
    storeName: 'Créations Artisanales',
    heroTitle: 'L\'art de la main',
    heroSubtitle: 'Pièces uniques créées par des artisans locaux',
    heroImage: 'https://images.unsplash.com/photo-1582735689369-22fe6a2b488c?w=1200&q=80',
    heroCta: 'Découvrir les créations',
    richTextHeading: 'Fait avec amour',
    richTextContent: 'Chaque pièce est unique. Sculptures, poteries, textiles — créés par des artisans de la Zone CFA.',
    aboutTitle: 'Artisans partenaires',
    aboutContent: 'Nous soutenons les créateurs locaux. Chaque achat valorise leur savoir-faire.',
    promoBanner: 'Pièces uniques — Chaque création est signée par l\'artisan',
    newsletterTitle: 'Ateliers et créations exclusives',
    contactEmail: 'contact@creations-artisanales.com',
    contactPhone: '+228 90 XX XX XX',
    colors: { primary: '#3e2723', secondary: '#5d4037', accent: '#8d6e63', bg: '#efebe9', text: '#3e2723' },
    products: [
      { id: '1', name: 'Sculpture en bois', price: 35000, priceLabel: '35 000 XOF', description: 'Pièce unique', imagePlaceholder: '🪵', imageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&q=80' },
      { id: '2', name: 'Panier tressé', price: 12000, priceLabel: '12 000 XOF', description: 'Fait main', imagePlaceholder: '🧺', imageUrl: 'https://images.unsplash.com/photo-1602874801006-4e6e9c7e0a78?w=600&q=80' },
      { id: '3', name: 'Bougie décorative', price: 5500, priceLabel: '5 500 XOF', description: 'Parfum naturel', imagePlaceholder: '🕯️', imageUrl: 'https://images.unsplash.com/photo-1602874801006-4e6e9c7e0a78?w=600&q=80' },
      { id: '4', name: 'Poterie traditionnelle', price: 18000, priceLabel: '18 000 XOF', description: 'Cuit au feu', imagePlaceholder: '🏺', imageUrl: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600&q=80' },
      { id: '5', name: 'Tapis tissé', price: 45000, priceLabel: '45 000 XOF', description: 'Couleurs vives', imagePlaceholder: '🎨', imageUrl: 'https://images.unsplash.com/photo-1558171813-63a45d37e129?w=600&q=80' },
      { id: '6', name: 'Bracelet cuir', price: 6500, priceLabel: '6 500 XOF', description: 'Artisanat local', imagePlaceholder: '📿', imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80' },
    ],
    footerTagline: 'Créations Artisanales — Fait avec amour',
    footerLinks: [
      { label: 'Accueil', href: '/' },
      { label: 'Produits', href: '/products' },
      { label: 'À propos', href: '/about' },
      { label: 'Contact', href: '/contact' },
    ],
    collections: [
      { id: 'all', name: 'Toutes les créations', productIds: ['1', '2', '3', '4', '5', '6'] },
    ],
  },
};
