import type { ThemeConfig } from './theme-types';

export const themesPart1: Record<string, ThemeConfig> = {
  classique: {
    id: 'classique',
    name: 'Classique',
    niche: 'Polyvalent',
    storeName: 'Ma Boutique',
    heroTitle: 'Bienvenue dans notre boutique',
    heroSubtitle: 'Découvrez une sélection soignée de produits de qualité',
    heroImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&q=80',
    heroCta: 'Voir les produits',
    richTextHeading: 'À propos de nous',
    richTextContent: 'Nous sélectionnons avec soin des produits de qualité pour vous. Que vous cherchiez un cadeau ou un essentiel du quotidien, vous trouverez ici ce qu\'il vous faut.',
    aboutTitle: 'Pourquoi nous choisir ?',
    aboutContent: 'Qualité garantie, livraison rapide et service client réactif. Votre satisfaction est notre priorité.',
    promoBanner: 'Livraison gratuite dès 25 000 XOF — Zone CFA',
    newsletterTitle: 'Restez informé de nos offres',
    contactEmail: 'contact@maboutique.com',
    contactPhone: '+221 33 XXX XX XX',
    colors: { primary: '#1a1a2e', secondary: '#16213e', accent: '#0f3460', bg: '#f8f9fa', text: '#212529' },
    products: [
      { id: '1', slug: 'produit-premium', name: 'Produit Premium', price: 15000, priceLabel: '15 000 XOF', description: 'Qualité supérieure', imagePlaceholder: '📦', imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80' },
      { id: '2', slug: 'essentiel-du-quotidien', name: 'Essentiel du quotidien', price: 8500, priceLabel: '8 500 XOF', description: 'Indispensable', imagePlaceholder: '✨', imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80' },
      { id: '3', slug: 'cadeau-ideal', name: 'Cadeau idéal', price: 25000, priceLabel: '25 000 XOF', description: 'Pour toutes les occasions', imagePlaceholder: '🎁', imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80' },
      { id: '4', slug: 'best-seller', name: 'Best-seller', price: 12000, priceLabel: '12 000 XOF', description: 'Le préféré de nos clients', imagePlaceholder: '⭐', imageUrl: 'https://images.unsplash.com/photo-1560343090-f0409e92791a?w=600&q=80' },
      { id: '5', slug: 'nouvelle-arrivee', name: 'Nouvelle arrivée', price: 18000, priceLabel: '18 000 XOF', description: 'Tout juste arrivé', imagePlaceholder: '🆕', imageUrl: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=600&q=80' },
      { id: '6', slug: 'promo-speciale', name: 'Promo spéciale', price: 9990, priceLabel: '9 990 XOF', description: 'Offre limitée', imagePlaceholder: '🔥', imageUrl: 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=600&q=80' },
    ],
    footerTagline: '© Ma Boutique — Tous droits réservés',
    footerLinks: [
      { label: 'Accueil', href: '/' },
      { label: 'Produits', href: '/collections/all' },
      { label: 'À propos', href: '/about' },
      { label: 'Contact', href: '/contact' },
    ],
    collections: [
      { id: 'all', slug: 'all', name: 'Tous les produits', productIds: ['1', '2', '3', '4', '5', '6'] },
      { id: 'best', slug: 'best-sellers', name: 'Best-sellers', productIds: ['4', '1', '3'] },
    ],
  },
  mode: {
    id: 'mode',
    name: 'Mode',
    niche: 'Vêtements & Accessoires',
    storeName: 'Style Africain',
    heroTitle: 'L\'élégance à portée de main',
    heroSubtitle: 'Collections tendance pour femmes et hommes',
    heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
    heroCta: 'Découvrir la collection',
    richTextHeading: 'Notre univers',
    richTextContent: 'Des vêtements et accessoires qui célèbrent la mode africaine. Des créations authentiques et modernes pour vous démarquer.',
    aboutTitle: 'Fait main & authentique',
    aboutContent: 'Chaque pièce est soigneusement sélectionnée. Des artisans locaux aux tissus premium.',
    promoBanner: 'Nouvelle collection printemps — -20% sur une sélection',
    newsletterTitle: 'Accédez en avant-première aux nouveautés',
    contactEmail: 'style@styleafricain.com',
    contactPhone: '+225 07 XX XX XX XX',
    colors: { primary: '#2d132c', secondary: '#801336', accent: '#c72c41', bg: '#faf5f6', text: '#2d132c' },
    products: [
      { id: '1', slug: 'robe-wax-imprime', name: 'Robe wax imprimé', price: 25000, priceLabel: '25 000 XOF', description: 'Tissu premium', imagePlaceholder: '👗', imageUrl: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80' },
      { id: '2', slug: 'sac-a-main-cuir', name: 'Sac à main cuir', price: 35000, priceLabel: '35 000 XOF', description: 'Fait main', imagePlaceholder: '👜', imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&q=80' },
      { id: '3', slug: 'boubou-brode', name: 'Boubou brodé', price: 45000, priceLabel: '45 000 XOF', description: 'Pièce unique', imagePlaceholder: '👘', imageUrl: 'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=600&q=80' },
      { id: '4', slug: 'sandalettes', name: 'Sandalettes', price: 15000, priceLabel: '15 000 XOF', description: 'Confortables', imagePlaceholder: '👡', imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80' },
      { id: '5', slug: 'pagne-assorti', name: 'Pagne assorti', price: 12000, priceLabel: '12 000 XOF', description: 'Coton africain', imagePlaceholder: '🧣', imageUrl: 'https://images.unsplash.com/photo-1558171813-63a45d37e129?w=600&q=80' },
      { id: '6', slug: 'bijoux-traditionnels', name: 'Bijoux traditionnels', price: 8000, priceLabel: '8 000 XOF', description: 'Artisanat local', imagePlaceholder: '📿', imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80' },
    ],
    footerTagline: 'Style Africain — Mode & Tradition',
    footerLinks: [
      { label: 'Accueil', href: '/' },
      { label: 'Collections', href: '/collections/all' },
      { label: 'À propos', href: '/about' },
      { label: 'Contact', href: '/contact' },
    ],
    collections: [
      { id: 'all', slug: 'all', name: 'Toute la collection', productIds: ['1', '2', '3', '4', '5', '6'] },
      { id: 'vetements', slug: 'vetements', name: 'Vêtements', productIds: ['1', '3', '5'] },
      { id: 'accessoires', slug: 'accessoires', name: 'Accessoires', productIds: ['2', '4', '6'] },
    ],
  },
  tech: {
    id: 'tech',
    name: 'Tech',
    niche: 'Électronique & Gadgets',
    storeName: 'TechZone CFA',
    heroTitle: 'La technologie à petits prix',
    heroSubtitle: 'Smartphones, accessoires et gadgets pour rester connecté',
    heroImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80',
    heroCta: 'Explorer le catalogue',
    richTextHeading: 'Connectez-vous',
    richTextContent: 'Une sélection de produits tech adaptés au marché africain. Smartphones, accessoires et gadgets à prix compétitifs.',
    aboutTitle: 'Garantie et SAV',
    aboutContent: 'Tous nos produits sont garantis. Service après-vente réactif dans toute la Zone CFA.',
    promoBanner: 'Paiement en 3x sans frais — Livraison express disponible',
    newsletterTitle: 'Offres tech et bons plans',
    contactEmail: 'support@techzonecfa.com',
    contactPhone: '+228 90 XX XX XX',
    colors: { primary: '#0d1b2a', secondary: '#1b263b', accent: '#00b4d8', bg: '#0d1b2a', text: '#e0e0e0' },
    products: [
      { id: '1', slug: 'smartphone-4g', name: 'Smartphone 4G', price: 75000, priceLabel: '75 000 XOF', description: 'Double SIM', imagePlaceholder: '📱', imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80' },
      { id: '2', slug: 'ecouteurs-bluetooth', name: 'Écouteurs Bluetooth', price: 12000, priceLabel: '12 000 XOF', description: 'Qualité audio HD', imagePlaceholder: '🎧', imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80' },
      { id: '3', slug: 'power-bank-20000mah', name: 'Power bank 20000mAh', price: 18000, priceLabel: '18 000 XOF', description: 'Charge rapide', imagePlaceholder: '🔋', imageUrl: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80' },
      { id: '4', slug: 'montre-connectee', name: 'Montre connectée', price: 25000, priceLabel: '25 000 XOF', description: 'Suivi santé', imagePlaceholder: '⌚', imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80' },
      { id: '5', slug: 'clavier-sans-fil', name: 'Clavier sans fil', price: 15000, priceLabel: '15 000 XOF', description: 'Ergonomique', imagePlaceholder: '⌨️', imageUrl: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=600&q=80' },
      { id: '6', slug: 'chargeur-multi-port', name: 'Chargeur multi-port', price: 8500, priceLabel: '8 500 XOF', description: '3 ports USB', imagePlaceholder: '🔌', imageUrl: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&q=80' },
    ],
    footerTagline: 'TechZone CFA — Connectez-vous à l\'essentiel',
    footerLinks: [
      { label: 'Accueil', href: '/' },
      { label: 'Produits', href: '/collections/all' },
      { label: 'À propos', href: '/about' },
      { label: 'Contact', href: '/contact' },
    ],
    collections: [
      { id: 'all', slug: 'all', name: 'Tous les produits', productIds: ['1', '2', '3', '4', '5', '6'] },
      { id: 'telephonie', slug: 'telephonie', name: 'Téléphonie', productIds: ['1', '2'] },
      { id: 'accessoires', slug: 'accessoires', name: 'Accessoires', productIds: ['3', '4', '5', '6'] },
    ],
  },
};
